//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "modes")]
pub enum Modes {
    #[sea_orm(string_value = "Cache")]
    Cache,
    #[sea_orm(string_value = "hash")]
    Hash,
    #[sea_orm(string_value = "map")]
    Map,
}
